# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "sha256-J5KzQdyHbPlT/jC+PoojiJ3iln6OfvfFLGhd8vp7IHQ=";
    aarch64-linux = "sha256-isHXimen4RpjzINw4shQA/nl/1Se6c8xdjkKvwpi+vo=";
    x86_64-darwin = "sha256-ScxhEpPFPrvW690TRWchNLMiYSU1y0Et8Tp3BHVfyrk=";
    aarch64-darwin = "sha256-B0W0Y+0Xrfbs0THh36qs4hcDPfX+ClEZEnC3/hQnAzw=";
  };

  urlMap = {
    x86_64-linux = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.2/hcp_archiver_Linux_x86_64.tar.gz";
    aarch64-linux = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.2/hcp_archiver_Linux_arm64.tar.gz";
    x86_64-darwin = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.2/hcp_archiver_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.2/hcp_archiver_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hcp_archiver";
  version = "0.12.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./hcp_archiver $out/bin/hcp_archiver
    installManPage ./man/hcp_archiver.1
    installShellCompletion ./completion/bash/hcp_archiver.bash
    installShellCompletion ./completion/zsh/_hcp_archiver
    installShellCompletion ./completion/fish/hcp_archiver.fish
  '';

  meta = {
    description = "Archives an HCP Terraform organization to plain files on disk";
    homepage = "https://git.jacobcolvin.com/hcp_archiver";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
