# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "sha256-Ren8GE0kNX+e3nkkzZSRjXuNqwK5JvKlRS5dWgbNBd0=";
    aarch64-linux = "sha256-FeIr6nWZVX6CXLj3lHh7ckm7yzmHxeSiKxOuN33xBfc=";
    x86_64-darwin = "sha256-JP5Bixb66eQuA+Z/H8wdrkZ/M77kGgX8fnlAvgugmRE=";
    aarch64-darwin = "sha256-YqVkZZCTTeJmLtK5YwirzShNM6Fbx6hxYUTFRSpc6XA=";
  };

  urlMap = {
    x86_64-linux = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.0/hcp_archiver_Linux_x86_64.tar.gz";
    aarch64-linux = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.0/hcp_archiver_Linux_arm64.tar.gz";
    x86_64-darwin = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.0/hcp_archiver_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://git.jacobcolvin.com/hcp_archiver/releases/download/v0.12.0/hcp_archiver_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hcp_archiver";
  version = "0.12.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./hcp_archiver $out/bin/hcp_archiver
    installManPage ./man/hcp_archiver.1
    installShellCompletion ./completion/bash/hcp_archiver.bash
    installShellCompletion ./completion/zsh/_hcp_archiver
    installShellCompletion ./completion/fish/hcp_archiver.fish
  '';

  meta = {
    description = "Archives an HCP Terraform organization to plain files on disk";
    homepage = "https://git.jacobcolvin.com/hcp_archiver";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
