# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0g93bbfz4sbv3rdxyl47dx4hz9vd2xzqdify0j5pxw53iprk8jdd";
    aarch64-linux = "0zw2i9ncvl8xvrh31k8bm1k8b6gsg4j1h45rv9fq4safccv28jxw";
    x86_64-darwin = "1bhnrpd1m7kkhh2y3awqg73945ay4vkcxad7y0bxizbv8mcwbvzx";
    aarch64-darwin = "1f4ipdj1hv1ywig4f2qqza04qf8g9py16993662rscyix2dqs1vv";
  };

  urlMap = {
    x86_64-linux = "https://github.com/macropower/kclipper/releases/download/v0.16.1/kclipper_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/macropower/kclipper/releases/download/v0.16.1/kclipper_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.16.1/kclipper_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.16.1/kclipper_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kclipper";
  version = "0.16.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kcl $out/bin/kcl
  '';

  system = system;

  meta = {
    description = "Kclipper Command Line Interface";
    homepage = "https://github.com/macropower/kclipper";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
