# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "02789mz29b8lb26w161m4vz391mz7ia4ylgl77s8pnm98gyky5ih";
    aarch64-linux = "14syabqc1xdbrh691sf48hd48q37xg5hxiy0b7cgkdja21rh278x";
    x86_64-darwin = "0c531gjyjnb44x7r1h09sl95g7la6f1imrgxwncva71c9acdmwia";
    aarch64-darwin = "146028m3jl9bgw2f7rmnx6xqmshq8c2xf1y773g4qd32712af97p";
  };

  urlMap = {
    x86_64-linux = "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kclipper";
  version = "0.16.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kcl $out/bin/kcl
  '';

  system = system;

  meta = {
    description = "Kclipper Command Line Interface";
    homepage = "https://github.com/macropower/kclipper";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
