# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, kcl-lsp
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "19hz7s1z342xaxpgjmigf40nbzyvy0azjna97fz3ia96algirbx2";
    aarch64-linux = "1r84jl7s3zn3a2ly4v9l912gsk59pvdmq7mrzq9q522f62w9zdf5";
    x86_64-darwin = "0iaxxr98ywxmcw6p56nx27s3xh1b1gpk1wgrl5vcg4zkkqc1npym";
    aarch64-darwin = "07585gqn5bg046vwx42mn2psg893f7hzxfazq8h7ya7pnn5xxd9x";
  };

  urlMap = {
    x86_64-linux = "https://github.com/macropower/kclipper/releases/download/v0.15.1/kclipper_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/macropower/kclipper/releases/download/v0.15.1/kclipper_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.15.1/kclipper_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.15.1/kclipper_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kclipper";
  version = "0.15.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kcl $out/bin/kcl
    wrapProgram $out/bin/kcl --prefix PATH : ${lib.makeBinPath ([ kcl-lsp ])}
  '';

  system = system;

  meta = {
    description = "Kclipper Command Line Interface";
    homepage = "https://github.com/macropower/kclipper";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
