# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0mak6c0qb8xkrk2nidfm8aiin6kwlmdrjvr6s7fvdq3vz2spgxln";
    aarch64-linux = "0yddf3paar2yncwiz3c3nr3zsipj0381vpmvy5vwclhdl9pjz1vv";
    x86_64-darwin = "1cml503g94v2j61kpxgwiamsskqpr3wjxbzzw5glbcqa4334pmyh";
    aarch64-darwin = "1d3q4q4r1dwyni35h3m6qcnb3xh2dfzhzszvwljbz1diqqg3wmsc";
  };

  urlMap = {
    x86_64-linux = "https://github.com/MacroPower/kat/releases/download/v0.26.0/kat_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/MacroPower/kat/releases/download/v0.26.0/kat_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/MacroPower/kat/releases/download/v0.26.0/kat_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/MacroPower/kat/releases/download/v0.26.0/kat_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kat";
  version = "0.26.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kat $out/bin/kat
    installManPage ./man/kat.1
    installShellCompletion ./completion/bash/kat.bash
    installShellCompletion ./completion/zsh/_kat
    installShellCompletion ./completion/fish/kat.fish
  '';

  system = system;

  meta = {
    description = "TUI for rendering, validating, and displaying local Kubernetes manifests";
    homepage = "https://github.com/MacroPower/kat/";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
