# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0xs7mn4c65lqlalprp4iy9f4fj64gf97y0gbk0j89fasy7va7ka4";
    aarch64-linux = "07nfimf16f5q21hgs51hgrq14gbxk1qsk7vasbg6z3ga1w1svifr";
    x86_64-darwin = "1j39h5svs37wdb61496mjy0v9vxfih1r322fnzw8x6z3wiy6v34m";
    aarch64-darwin = "0nzj94c4l5kq3i0ky3mfrv62bs7d4bra6qnq3hlmv1rzm3mvgljr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kat";
  version = "0.13.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kat $out/bin/kat
  '';

  system = system;

  meta = {
    description = "TUI for rendering, validating, and displaying local Kubernetes manifests";
    homepage = "https://github.com/MacroPower/kat/";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
