# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0vnkqd1kp1hwgn890cgd6wk19gs5k4sc0h22vvl4kl5bgspr505b";
    aarch64-linux = "0hwnqlscqfg8p6a3wsf6lph99w4wsirsyfk8bxp01pd4sy5i8pwf";
    x86_64-darwin = "1ysdv5akfz08cvb1k36zib8hjvkkb4prrv4z4h9k96kg5ph72hm3";
    aarch64-darwin = "0fs62mxydfsjxzldrj21a337l76l71in1fnzj8qfkf75gshgq52z";
  };

  urlMap = {
    x86_64-linux = "https://github.com/MacroPower/kat/releases/download/v0.15.0/kat_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/MacroPower/kat/releases/download/v0.15.0/kat_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/MacroPower/kat/releases/download/v0.15.0/kat_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/MacroPower/kat/releases/download/v0.15.0/kat_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kat";
  version = "0.15.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kat $out/bin/kat
  '';

  system = system;

  meta = {
    description = "TUI for rendering, validating, and displaying local Kubernetes manifests";
    homepage = "https://github.com/MacroPower/kat/";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
