# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  envoy-bin,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "sha256-KQ+YRutavZhxmO6atkqVINgaukPxTkG+aF4HyOZx3aY=";
    aarch64-linux = "sha256-vF/pd5HCg4YSpVxJNyECudxlxNOpmvA7zNBzTPAsvUM=";
  };

  urlMap = {
    x86_64-linux = "https://github.com/macropower/terrarium/releases/download/v0.6.2/terrarium_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/macropower/terrarium/releases/download/v0.6.2/terrarium_Linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "terrarium";
  version = "0.6.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./terrarium $out/bin/terrarium
    wrapProgram $out/bin/terrarium --prefix PATH : ${lib.makeBinPath ([ envoy-bin ])}
  '';

  meta = {
    description = "Secure container environment using Envoy as an L7 egress gateway";
    homepage = "https://github.com/macropower/terrarium";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
