# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0ycarl71m1f7a94r5113s9ad5lz7zycl2ggv508w1h5fdi7qn6y5";
    aarch64-linux = "1pqiqqak1v0ch0326qh1992cq40pq6az5w2k3005wqn2fwc4ncq4";
    x86_64-darwin = "0cnzm2dmn999dhr7q1859i19y5lir88w2hz04ki71y7b1iivriy5";
    aarch64-darwin = "11p7z1bp994i810gqqid857mpbbc1gx1q82m080yi78xkb7cs9z2";
  };

  urlMap = {
    x86_64-linux = "https://github.com/macropower/kclipper/releases/download/v0.17.0/kclipper_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/macropower/kclipper/releases/download/v0.17.0/kclipper_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.17.0/kclipper_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/macropower/kclipper/releases/download/v0.17.0/kclipper_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kcl-lsp";
  version = "0.17.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kcl-language-server $out/bin/kcl-language-server
  '';

  system = system;

  meta = {
    description = "KCL Language Server";
    homepage = "https://github.com/kcl-lang/kcl";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
